name: Test BOM Snapshots

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master


concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true


jobs:

  generate:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Grab pnpm version
        id: pnpm-version
        run: |
          pnpm_version=$(cat package.json | jq '.packageManager|match("(?<=pnpm@)\\d+.\\d+.\\d+")|.string')
          echo "PNPM=$pnpm_version" >> "$GITHUB_ENV"

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM }}

      -  name: cdxgen, sdkman, custom-json-diff installs
         shell: bash
         env:
           SHELL: bash
         run: |
           cdxgen_tarball=$(pnpm pack | tail -1)
           npm install -g "$cdxgen_tarball"
           python -m pip install --upgrade pip
           python -m pip install pytest
           git clone https://github.com/appthreat/cdxgen-samples.git /home/runner/work/samples
           python -m pip install custom-json-diff
           curl -s "https://get.sdkman.io" | bash
           source "/home/runner/.sdkman/bin/sdkman-init.sh"

